// Code autogenerated by mockery v3
//
// Do not manually edit the content of this file.

// Package findertest contains autogenerated mocks.
package findertest

import "oss.indeed.com/go/modprox/registry/internal/tools/finder"
import "github.com/stretchr/testify/mock"

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

// Find provides a mock function with given fields: mockeryArg0
func (mockerySelf *Finder) Find(mockeryArg0 string) (*finder.Result, error) {
	ret := mockerySelf.Called(mockeryArg0)

	var r0 *finder.Result
	if rf, ok := ret.Get(0).(func(string) *finder.Result); ok {
		r0 = rf(mockeryArg0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finder.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(mockeryArg0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
