// Code autogenerated by mockery v3
//
// Do not manually edit the content of this file.

// Package findertest contains autogenerated mocks.
package findertest

import "github.com/modprox/mp/registry/internal/tools/finder"
import "github.com/stretchr/testify/mock"

// Versions is an autogenerated mock type for the Versions type
type Versions struct {
	mock.Mock
}

// Request provides a mock function with given fields: source
func (mockerySelf *Versions) Request(source string) (*finder.Result, error) {
	ret := mockerySelf.Called(source)

	var r0 *finder.Result
	if rf, ok := ret.Get(0).(func(string) *finder.Result); ok {
		r0 = rf(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finder.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
