package proxies

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock"
)

// PrunerMock implements Pruner
type PrunerMock struct {
	t minimock.Tester

	funcPrune          func(t1 time.Time) (err error)
	afterPruneCounter  uint64
	beforePruneCounter uint64
	PruneMock          mPrunerMockPrune
}

// NewPrunerMock returns a mock for Pruner
func NewPrunerMock(t minimock.Tester) *PrunerMock {
	m := &PrunerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}
	m.PruneMock = mPrunerMockPrune{mock: m}

	return m
}

type mPrunerMockPrune struct {
	mock               *PrunerMock
	defaultExpectation *PrunerMockPruneExpectation
	expectations       []*PrunerMockPruneExpectation
}

// PrunerMockPruneExpectation specifies expectation struct of the Pruner.Prune
type PrunerMockPruneExpectation struct {
	mock    *PrunerMock
	params  *PrunerMockPruneParams
	results *PrunerMockPruneResults
	Counter uint64
}

// PrunerMockPruneParams contains parameters of the Pruner.Prune
type PrunerMockPruneParams struct {
	t1 time.Time
}

// PrunerMockPruneResults contains results of the Pruner.Prune
type PrunerMockPruneResults struct {
	err error
}

// Expect sets up expected params for Pruner.Prune
func (m *mPrunerMockPrune) Expect(t1 time.Time) *mPrunerMockPrune {
	if m.mock.funcPrune != nil {
		m.mock.t.Fatalf("PrunerMock.Prune mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &PrunerMockPruneExpectation{}
	}

	m.defaultExpectation.params = &PrunerMockPruneParams{t1}
	for _, e := range m.expectations {
		if minimock.Equal(e.params, m.defaultExpectation.params) {
			m.mock.t.Fatalf("Expectation set by When has same params: %#v", *m.defaultExpectation.params)
		}
	}

	return m
}

// Return sets up results that will be returned by Pruner.Prune
func (m *mPrunerMockPrune) Return(err error) *PrunerMock {
	if m.mock.funcPrune != nil {
		m.mock.t.Fatalf("PrunerMock.Prune mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &PrunerMockPruneExpectation{mock: m.mock}
	}
	m.defaultExpectation.results = &PrunerMockPruneResults{err}
	return m.mock
}

//Set uses given function f to mock the Pruner.Prune method
func (m *mPrunerMockPrune) Set(f func(t1 time.Time) (err error)) *PrunerMock {
	if m.defaultExpectation != nil {
		m.mock.t.Fatalf("Default expectation is already set for the Pruner.Prune method")
	}

	if len(m.expectations) > 0 {
		m.mock.t.Fatalf("Some expectations are already set for the Pruner.Prune method")
	}

	m.mock.funcPrune = f
	return m.mock
}

// When sets expectation for the Pruner.Prune which will trigger the result defined by the following
// Then helper
func (m *mPrunerMockPrune) When(t1 time.Time) *PrunerMockPruneExpectation {
	if m.mock.funcPrune != nil {
		m.mock.t.Fatalf("PrunerMock.Prune mock is already set by Set")
	}

	expectation := &PrunerMockPruneExpectation{
		mock:   m.mock,
		params: &PrunerMockPruneParams{t1},
	}
	m.expectations = append(m.expectations, expectation)
	return expectation
}

// Then sets up Pruner.Prune return parameters for the expectation previously defined by the When method
func (e *PrunerMockPruneExpectation) Then(err error) *PrunerMock {
	e.results = &PrunerMockPruneResults{err}
	return e.mock
}

// Prune implements Pruner
func (m *PrunerMock) Prune(t1 time.Time) (err error) {
	mm_atomic.AddUint64(&m.beforePruneCounter, 1)
	defer mm_atomic.AddUint64(&m.afterPruneCounter, 1)

	for _, e := range m.PruneMock.expectations {
		if minimock.Equal(*e.params, PrunerMockPruneParams{t1}) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if m.PruneMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&m.PruneMock.defaultExpectation.Counter, 1)
		want := m.PruneMock.defaultExpectation.params
		got := PrunerMockPruneParams{t1}
		if want != nil && !minimock.Equal(*want, got) {
			m.t.Errorf("PrunerMock.Prune got unexpected parameters, want: %#v, got: %#v%s\n", *want, got, minimock.Diff(*want, got))
		}

		results := m.PruneMock.defaultExpectation.results
		if results == nil {
			m.t.Fatal("No results are set for the PrunerMock.Prune")
		}
		return (*results).err
	}
	if m.funcPrune != nil {
		return m.funcPrune(t1)
	}
	m.t.Fatalf("Unexpected call to PrunerMock.Prune. %v", t1)
	return
}

// PruneAfterCounter returns a count of finished PrunerMock.Prune invocations
func (m *PrunerMock) PruneAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&m.afterPruneCounter)
}

// PruneBeforeCounter returns a count of PrunerMock.Prune invocations
func (m *PrunerMock) PruneBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&m.beforePruneCounter)
}

// MinimockPruneDone returns true if the count of the Prune invocations corresponds
// the number of defined expectations
func (m *PrunerMock) MinimockPruneDone() bool {
	for _, e := range m.PruneMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PruneMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPruneCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPrune != nil && mm_atomic.LoadUint64(&m.afterPruneCounter) < 1 {
		return false
	}
	return true
}

// MinimockPruneInspect logs each unmet expectation
func (m *PrunerMock) MinimockPruneInspect() {
	for _, e := range m.PruneMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PrunerMock.Prune with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PruneMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPruneCounter) < 1 {
		m.t.Errorf("Expected call to PrunerMock.Prune with params: %#v", *m.PruneMock.defaultExpectation.params)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPrune != nil && mm_atomic.LoadUint64(&m.afterPruneCounter) < 1 {
		m.t.Error("Expected call to PrunerMock.Prune")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PrunerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockPruneInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PrunerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PrunerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPruneDone()
}
