package finder

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock"
)

// FinderMock implements Finder
type FinderMock struct {
	t minimock.Tester

	funcFind          func(s1 string) (rp1 *Result, err error)
	afterFindCounter  uint64
	beforeFindCounter uint64
	FindMock          mFinderMockFind
}

// NewFinderMock returns a mock for Finder
func NewFinderMock(t minimock.Tester) *FinderMock {
	m := &FinderMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}
	m.FindMock = mFinderMockFind{mock: m}

	return m
}

type mFinderMockFind struct {
	mock               *FinderMock
	defaultExpectation *FinderMockFindExpectation
	expectations       []*FinderMockFindExpectation
}

// FinderMockFindExpectation specifies expectation struct of the Finder.Find
type FinderMockFindExpectation struct {
	mock    *FinderMock
	params  *FinderMockFindParams
	results *FinderMockFindResults
	Counter uint64
}

// FinderMockFindParams contains parameters of the Finder.Find
type FinderMockFindParams struct {
	s1 string
}

// FinderMockFindResults contains results of the Finder.Find
type FinderMockFindResults struct {
	rp1 *Result
	err error
}

// Expect sets up expected params for Finder.Find
func (m *mFinderMockFind) Expect(s1 string) *mFinderMockFind {
	if m.mock.funcFind != nil {
		m.mock.t.Fatalf("FinderMock.Find mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &FinderMockFindExpectation{}
	}

	m.defaultExpectation.params = &FinderMockFindParams{s1}
	for _, e := range m.expectations {
		if minimock.Equal(e.params, m.defaultExpectation.params) {
			m.mock.t.Fatalf("Expectation set by When has same params: %#v", *m.defaultExpectation.params)
		}
	}

	return m
}

// Return sets up results that will be returned by Finder.Find
func (m *mFinderMockFind) Return(rp1 *Result, err error) *FinderMock {
	if m.mock.funcFind != nil {
		m.mock.t.Fatalf("FinderMock.Find mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &FinderMockFindExpectation{mock: m.mock}
	}
	m.defaultExpectation.results = &FinderMockFindResults{rp1, err}
	return m.mock
}

//Set uses given function f to mock the Finder.Find method
func (m *mFinderMockFind) Set(f func(s1 string) (rp1 *Result, err error)) *FinderMock {
	if m.defaultExpectation != nil {
		m.mock.t.Fatalf("Default expectation is already set for the Finder.Find method")
	}

	if len(m.expectations) > 0 {
		m.mock.t.Fatalf("Some expectations are already set for the Finder.Find method")
	}

	m.mock.funcFind = f
	return m.mock
}

// When sets expectation for the Finder.Find which will trigger the result defined by the following
// Then helper
func (m *mFinderMockFind) When(s1 string) *FinderMockFindExpectation {
	if m.mock.funcFind != nil {
		m.mock.t.Fatalf("FinderMock.Find mock is already set by Set")
	}

	expectation := &FinderMockFindExpectation{
		mock:   m.mock,
		params: &FinderMockFindParams{s1},
	}
	m.expectations = append(m.expectations, expectation)
	return expectation
}

// Then sets up Finder.Find return parameters for the expectation previously defined by the When method
func (e *FinderMockFindExpectation) Then(rp1 *Result, err error) *FinderMock {
	e.results = &FinderMockFindResults{rp1, err}
	return e.mock
}

// Find implements Finder
func (m *FinderMock) Find(s1 string) (rp1 *Result, err error) {
	mm_atomic.AddUint64(&m.beforeFindCounter, 1)
	defer mm_atomic.AddUint64(&m.afterFindCounter, 1)

	for _, e := range m.FindMock.expectations {
		if minimock.Equal(*e.params, FinderMockFindParams{s1}) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if m.FindMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&m.FindMock.defaultExpectation.Counter, 1)
		want := m.FindMock.defaultExpectation.params
		got := FinderMockFindParams{s1}
		if want != nil && !minimock.Equal(*want, got) {
			m.t.Errorf("FinderMock.Find got unexpected parameters, want: %#v, got: %#v%s\n", *want, got, minimock.Diff(*want, got))
		}

		results := m.FindMock.defaultExpectation.results
		if results == nil {
			m.t.Fatal("No results are set for the FinderMock.Find")
		}
		return (*results).rp1, (*results).err
	}
	if m.funcFind != nil {
		return m.funcFind(s1)
	}
	m.t.Fatalf("Unexpected call to FinderMock.Find. %v", s1)
	return
}

// FindAfterCounter returns a count of finished FinderMock.Find invocations
func (m *FinderMock) FindAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&m.afterFindCounter)
}

// FindBeforeCounter returns a count of FinderMock.Find invocations
func (m *FinderMock) FindBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&m.beforeFindCounter)
}

// MinimockFindDone returns true if the count of the Find invocations corresponds
// the number of defined expectations
func (m *FinderMock) MinimockFindDone() bool {
	for _, e := range m.FindMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FindMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFindCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFind != nil && mm_atomic.LoadUint64(&m.afterFindCounter) < 1 {
		return false
	}
	return true
}

// MinimockFindInspect logs each unmet expectation
func (m *FinderMock) MinimockFindInspect() {
	for _, e := range m.FindMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FinderMock.Find with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FindMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFindCounter) < 1 {
		if m.FindMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to FinderMock.Find")
		} else {
			m.t.Errorf("Expected call to FinderMock.Find with params: %#v", *m.FindMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFind != nil && mm_atomic.LoadUint64(&m.afterFindCounter) < 1 {
		m.t.Error("Expected call to FinderMock.Find")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *FinderMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockFindInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *FinderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *FinderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockFindDone()
}
