package registry

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"io"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock"
)

// ClientMock implements Client
type ClientMock struct {
	t minimock.Tester

	funcGet          func(path string, rw io.Writer) (err error)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mClientMockGet

	funcPost          func(path string, body io.Reader, rw io.Writer) (err error)
	afterPostCounter  uint64
	beforePostCounter uint64
	PostMock          mClientMockPost
}

// NewClientMock returns a mock for Client
func NewClientMock(t minimock.Tester) *ClientMock {
	m := &ClientMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}
	m.GetMock = mClientMockGet{mock: m}
	m.PostMock = mClientMockPost{mock: m}

	return m
}

type mClientMockGet struct {
	mock               *ClientMock
	defaultExpectation *ClientMockGetExpectation
	expectations       []*ClientMockGetExpectation
}

// ClientMockGetExpectation specifies expectation struct of the Client.Get
type ClientMockGetExpectation struct {
	mock    *ClientMock
	params  *ClientMockGetParams
	results *ClientMockGetResults
	Counter uint64
}

// ClientMockGetParams contains parameters of the Client.Get
type ClientMockGetParams struct {
	path string
	rw   io.Writer
}

// ClientMockGetResults contains results of the Client.Get
type ClientMockGetResults struct {
	err error
}

// Expect sets up expected params for Client.Get
func (m *mClientMockGet) Expect(path string, rw io.Writer) *mClientMockGet {
	if m.mock.funcGet != nil {
		m.mock.t.Fatalf("ClientMock.Get mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &ClientMockGetExpectation{}
	}

	m.defaultExpectation.params = &ClientMockGetParams{path, rw}
	for _, e := range m.expectations {
		if minimock.Equal(e.params, m.defaultExpectation.params) {
			m.mock.t.Fatalf("Expectation set by When has same params: %#v", *m.defaultExpectation.params)
		}
	}

	return m
}

// Return sets up results that will be returned by Client.Get
func (m *mClientMockGet) Return(err error) *ClientMock {
	if m.mock.funcGet != nil {
		m.mock.t.Fatalf("ClientMock.Get mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &ClientMockGetExpectation{mock: m.mock}
	}
	m.defaultExpectation.results = &ClientMockGetResults{err}
	return m.mock
}

//Set uses given function f to mock the Client.Get method
func (m *mClientMockGet) Set(f func(path string, rw io.Writer) (err error)) *ClientMock {
	if m.defaultExpectation != nil {
		m.mock.t.Fatalf("Default expectation is already set for the Client.Get method")
	}

	if len(m.expectations) > 0 {
		m.mock.t.Fatalf("Some expectations are already set for the Client.Get method")
	}

	m.mock.funcGet = f
	return m.mock
}

// When sets expectation for the Client.Get which will trigger the result defined by the following
// Then helper
func (m *mClientMockGet) When(path string, rw io.Writer) *ClientMockGetExpectation {
	if m.mock.funcGet != nil {
		m.mock.t.Fatalf("ClientMock.Get mock is already set by Set")
	}

	expectation := &ClientMockGetExpectation{
		mock:   m.mock,
		params: &ClientMockGetParams{path, rw},
	}
	m.expectations = append(m.expectations, expectation)
	return expectation
}

// Then sets up Client.Get return parameters for the expectation previously defined by the When method
func (e *ClientMockGetExpectation) Then(err error) *ClientMock {
	e.results = &ClientMockGetResults{err}
	return e.mock
}

// Get implements Client
func (m *ClientMock) Get(path string, rw io.Writer) (err error) {
	mm_atomic.AddUint64(&m.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&m.afterGetCounter, 1)

	for _, e := range m.GetMock.expectations {
		if minimock.Equal(*e.params, ClientMockGetParams{path, rw}) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if m.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&m.GetMock.defaultExpectation.Counter, 1)
		want := m.GetMock.defaultExpectation.params
		got := ClientMockGetParams{path, rw}
		if want != nil && !minimock.Equal(*want, got) {
			m.t.Errorf("ClientMock.Get got unexpected parameters, want: %#v, got: %#v%s\n", *want, got, minimock.Diff(*want, got))
		}

		results := m.GetMock.defaultExpectation.results
		if results == nil {
			m.t.Fatal("No results are set for the ClientMock.Get")
		}
		return (*results).err
	}
	if m.funcGet != nil {
		return m.funcGet(path, rw)
	}
	m.t.Fatalf("Unexpected call to ClientMock.Get. %v %v", path, rw)
	return
}

// GetAfterCounter returns a count of finished ClientMock.Get invocations
func (m *ClientMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&m.afterGetCounter)
}

// GetBeforeCounter returns a count of ClientMock.Get invocations
func (m *ClientMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&m.beforeGetCounter)
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *ClientMock) MinimockGetDone() bool {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetInspect logs each unmet expectation
func (m *ClientMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ClientMock.Get with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		m.t.Errorf("Expected call to ClientMock.Get with params: %#v", *m.GetMock.defaultExpectation.params)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		m.t.Error("Expected call to ClientMock.Get")
	}
}

type mClientMockPost struct {
	mock               *ClientMock
	defaultExpectation *ClientMockPostExpectation
	expectations       []*ClientMockPostExpectation
}

// ClientMockPostExpectation specifies expectation struct of the Client.Post
type ClientMockPostExpectation struct {
	mock    *ClientMock
	params  *ClientMockPostParams
	results *ClientMockPostResults
	Counter uint64
}

// ClientMockPostParams contains parameters of the Client.Post
type ClientMockPostParams struct {
	path string
	body io.Reader
	rw   io.Writer
}

// ClientMockPostResults contains results of the Client.Post
type ClientMockPostResults struct {
	err error
}

// Expect sets up expected params for Client.Post
func (m *mClientMockPost) Expect(path string, body io.Reader, rw io.Writer) *mClientMockPost {
	if m.mock.funcPost != nil {
		m.mock.t.Fatalf("ClientMock.Post mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &ClientMockPostExpectation{}
	}

	m.defaultExpectation.params = &ClientMockPostParams{path, body, rw}
	for _, e := range m.expectations {
		if minimock.Equal(e.params, m.defaultExpectation.params) {
			m.mock.t.Fatalf("Expectation set by When has same params: %#v", *m.defaultExpectation.params)
		}
	}

	return m
}

// Return sets up results that will be returned by Client.Post
func (m *mClientMockPost) Return(err error) *ClientMock {
	if m.mock.funcPost != nil {
		m.mock.t.Fatalf("ClientMock.Post mock is already set by Set")
	}

	if m.defaultExpectation == nil {
		m.defaultExpectation = &ClientMockPostExpectation{mock: m.mock}
	}
	m.defaultExpectation.results = &ClientMockPostResults{err}
	return m.mock
}

//Set uses given function f to mock the Client.Post method
func (m *mClientMockPost) Set(f func(path string, body io.Reader, rw io.Writer) (err error)) *ClientMock {
	if m.defaultExpectation != nil {
		m.mock.t.Fatalf("Default expectation is already set for the Client.Post method")
	}

	if len(m.expectations) > 0 {
		m.mock.t.Fatalf("Some expectations are already set for the Client.Post method")
	}

	m.mock.funcPost = f
	return m.mock
}

// When sets expectation for the Client.Post which will trigger the result defined by the following
// Then helper
func (m *mClientMockPost) When(path string, body io.Reader, rw io.Writer) *ClientMockPostExpectation {
	if m.mock.funcPost != nil {
		m.mock.t.Fatalf("ClientMock.Post mock is already set by Set")
	}

	expectation := &ClientMockPostExpectation{
		mock:   m.mock,
		params: &ClientMockPostParams{path, body, rw},
	}
	m.expectations = append(m.expectations, expectation)
	return expectation
}

// Then sets up Client.Post return parameters for the expectation previously defined by the When method
func (e *ClientMockPostExpectation) Then(err error) *ClientMock {
	e.results = &ClientMockPostResults{err}
	return e.mock
}

// Post implements Client
func (m *ClientMock) Post(path string, body io.Reader, rw io.Writer) (err error) {
	mm_atomic.AddUint64(&m.beforePostCounter, 1)
	defer mm_atomic.AddUint64(&m.afterPostCounter, 1)

	for _, e := range m.PostMock.expectations {
		if minimock.Equal(*e.params, ClientMockPostParams{path, body, rw}) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if m.PostMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&m.PostMock.defaultExpectation.Counter, 1)
		want := m.PostMock.defaultExpectation.params
		got := ClientMockPostParams{path, body, rw}
		if want != nil && !minimock.Equal(*want, got) {
			m.t.Errorf("ClientMock.Post got unexpected parameters, want: %#v, got: %#v%s\n", *want, got, minimock.Diff(*want, got))
		}

		results := m.PostMock.defaultExpectation.results
		if results == nil {
			m.t.Fatal("No results are set for the ClientMock.Post")
		}
		return (*results).err
	}
	if m.funcPost != nil {
		return m.funcPost(path, body, rw)
	}
	m.t.Fatalf("Unexpected call to ClientMock.Post. %v %v %v", path, body, rw)
	return
}

// PostAfterCounter returns a count of finished ClientMock.Post invocations
func (m *ClientMock) PostAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&m.afterPostCounter)
}

// PostBeforeCounter returns a count of ClientMock.Post invocations
func (m *ClientMock) PostBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&m.beforePostCounter)
}

// MinimockPostDone returns true if the count of the Post invocations corresponds
// the number of defined expectations
func (m *ClientMock) MinimockPostDone() bool {
	for _, e := range m.PostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PostMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPostCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPost != nil && mm_atomic.LoadUint64(&m.afterPostCounter) < 1 {
		return false
	}
	return true
}

// MinimockPostInspect logs each unmet expectation
func (m *ClientMock) MinimockPostInspect() {
	for _, e := range m.PostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ClientMock.Post with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PostMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPostCounter) < 1 {
		m.t.Errorf("Expected call to ClientMock.Post with params: %#v", *m.PostMock.defaultExpectation.params)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPost != nil && mm_atomic.LoadUint64(&m.afterPostCounter) < 1 {
		m.t.Error("Expected call to ClientMock.Post")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ClientMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockGetInspect()

		m.MinimockPostInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetDone() &&
		m.MinimockPostDone()
}
